Repository PhilsLab/aprog-statdriver, pull requests merged in 2020-05, with the labels that each got.

#23 switch default time of entries.date to current unix epoch
  src/database/statdriver.sql
Labels: bug

#30 added signup-handler, login-errors and already tested
  src/controllers/auth.js
  src/middlewares/authentication.js
  src/router.js
  src/templates/login.ejs
  src/templates/signup.ejs
Labels: feature

#32 fix conditional base redirect
  src/router.js
Labels: bug

#33 fix user ID owner validation for scoreboard viewing
  src/controllers/scoreboard.js
Labels: bug

#29 feature-loginpage
  .gitignore
  .idea/dataSources.local.xml
  .idea/dataSources/0a5ebc72-14d7-44f9-91e5-8491e5303df5.xml
  .idea/dataSources/b3f93c86-6e3f-4f0e-a801-e0949de2b278.xml
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/css/common.css
  src/assets/css/login.css
  src/assets/fonts/pressstart2p-webfont.woff
  src/assets/fonts/pressstart2p-webfont.woff2
  src/templates/login.ejs
Labels: feature

#40 remove .DS_Store files
  src/.DS_Store
  src/assets/.DS_Store
Labels: misc

#42 added dashboard routes + handler
  src/controllers/dashboard.js
Labels: feature

#43 add a demo UI for recording and displaying scores of via the StatDriver API
  .idea/misc.xml
  .idea/runConfigurations/mockui.xml
  package-lock.json
  package.json
  src/index.js
  src/mockui/.gitignore
  src/mockui/package-lock.json
  src/mockui/package.json
  src/mockui/public/favicon.ico
  src/mockui/public/index.html
  src/mockui/src/App.js
  src/mockui/src/components/CredentialForm.js
  src/mockui/src/components/CredentialForm.module.css
  src/mockui/src/components/ScoreBox.js
  src/mockui/src/components/ScoreBox.module.css
  src/mockui/src/components/ScoreForm.js
  src/mockui/src/components/ScoreForm.module.css
  src/mockui/src/index.css
  src/mockui/src/index.js
  src/router.js
Labels: feature, misc

#45 implement redirection to previously visited page
  src/controllers/auth.js
  src/templates/login.ejs
Labels: bug

#46 add nodemon for development
  .idea/runConfigurations/start__dev_.xml
  package-lock.json
  package.json
  src/index.js
Labels: misc

#50 insert key generator for initial API keys
  src/controllers/game.js
Labels: feature

#36 add dashboard design
  src/assets/css/dashboard.css
  src/assets/img/2.jpg
  src/templates/dashboard.ejs
Labels: feature

#47 feature-signup
  src/assets/css/signup.css
  src/templates/signup.ejs
Labels: feature

#52 add link to corresponding game
  src/templates/dashboard.ejs
Labels: bug

#53 add game short statistics
  src/controllers/dashboard.js
  src/templates/dashboard.ejs
Labels: feature

#54 fix dashboard query not showing games without scoreboards
  src/controllers/dashboard.js
Labels: bug

#55 fix email field
  src/templates/signup.ejs
Labels: bug

#56 fix password confirmation field
  src/templates/signup.ejs
Labels: bug

#57 implement profile-page
  src/controllers/profile.js
  src/router.js
  src/templates/change-password.ejs
  src/templates/dashboard.ejs
  src/templates/profile.ejs
Labels: feature

#58 add embed design (dark+light)
  src/assets/css/embed.css
  src/assets/css/embed.dark.css
  src/assets/css/embed.light.css
  src/controllers/embed.js
  src/templates/embed.ejs
Labels: feature

#59 feature-newgame
  src/assets/css/new-game.css
  src/assets/css/signup.css
  src/templates/new-game.ejs
Labels: feature

#63 add docker gitignore
  .gitignore
Labels: misc

#65 add mockui to docker build spec
  Dockerfile
Labels: bug

#66 implement game/scoreboard deletion via POST
  src/controllers/game.js
  src/controllers/scoreboard.js
  src/templates/dashboard.ejs
Labels: bug

#69 add per-day stats for a scoreboard
  src/controllers/scoreboard.js
  src/templates/scoreboard.ejs
Labels: feature

#62 feature-profile
  src/assets/css/profile.css
  src/templates/profile.ejs
Labels: feature

#70 feature-404
  src/assets/css/404.css
  src/templates/404.ejs
Labels: feature

#73 feature-newscoreboard1
  src/assets/css/new-scoreboard.css
  src/templates/new-scoreboard.ejs
Labels: feature

#74 Improve codestyle
  src/controllers/api.js
  src/controllers/auth.js
  src/controllers/game.js
  src/controllers/profile.js
  src/index.js
  src/middlewares/authentication.js
  src/middlewares/database.js
  src/mockui/public/index.html
  src/mockui/src/index.js
  src/router.js
  src/seeder.js
Labels: misc

#71 Feature newpassword
  src/assets/css/change-password.css
  src/templates/change-password.ejs
Labels: feature

#75 feature-dashboard1
  src/assets/css/dashboard.css
  src/assets/img/icon.png
  src/templates/dashboard.ejs
Labels: bug

#76 feature-scoreboard
  src/assets/css/.gitkeep
  src/assets/css/Chart.min.css
  src/assets/css/scoreboard.css
  src/assets/fonts/.gitkeep
  src/assets/img/.gitkeep
  src/assets/img/2.jpg
  src/assets/js/.gitkeep
  src/assets/js/Chart.bundle.min.js
  src/controllers/scoreboard.js
  src/templates/scoreboard.ejs
Labels: feature

#79 Refine scoreboard
  src/assets/css/scoreboard.css
  src/templates/scoreboard.ejs
Labels: feature

#78 feature-dashboard2
  src/assets/css/dashboard.css
  src/templates/dashboard.ejs
Labels: feature

#77 feature-allscoreboards
  src/assets/css/game.css
  src/templates/game.ejs
Labels: feature

#80 add singlestats
  src/assets/css/scoreboard.css
  src/controllers/scoreboard.js
  src/templates/scoreboard.ejs
Labels: feature

#81 add dashboard link
  src/templates/scoreboard.ejs
Labels: feature

#82 fix formatting and dashboard link
  src/templates/game.ejs
Labels: feature

#84 fix title for control segment
  src/templates/scoreboard.ejs
Labels: bug

#85 add API access fields and refactor with jQuery
  src/controllers/scoreboard.js
  src/templates/scoreboard.ejs
Labels: feature

#88 style custom checkbox element
  src/assets/css/scoreboard.css
  src/templates/scoreboard.ejs
Labels: feature

#89 fix day range calculation
  src/controllers/scoreboard.js
  src/templates/scoreboard.ejs
Labels: bug

#90 add link to signup page
  src/assets/css/login.css
  src/templates/login.ejs
Labels: bug

#91 fix default time for new submissions
  src/controllers/api.js
Labels: bug

#92 remove debug console log
  src/controllers/scoreboard.js
Labels: misc

#93 several design fixes
  src/assets/css/game.css
  src/assets/css/login.css
  src/assets/css/scoreboard.css
Labels: bug
